{% set name = "matrix_utils" %}
{% set version = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 006bd402274e24a0980bae06d0141de8f50371149268df375f0244ca08d55ce7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip

  run:
    - bw_processing >=0.9.5
    - fsspec
    - numpy
    - python >=3.9
    - scipy
    - stats_arrays

test:
  imports:
    - {{ name }}
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/brightway-lca/matrix_utils
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Utilities to build and iterate on matrices using datapackages '
  doc_url: https://3.docs.brightwaylca.org/
  dev_url: https://github.com/brightway-lca/matrix_utils

extra:
  recipe-maintainers:
    - cmutel
