{% set name = "matrix_utils" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5e91a25018808f3d8fcda67a30ed2b7ebbfaf083e33a7cbfdd4e311152409465

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - numpy
    - python >=3.6
    - scipy
    - pandas
    - bw_processing >=0.8
    - stats_arrays

test:
  imports:
    - {{ name }}
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/brightway-lca/matrix_utils
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Utilities to build and iterate on matrices using datapackages '
  doc_url: https://3.docs.brightwaylca.org/
  dev_url: https://github.com/brightway-lca/matrix_utils

extra:
  recipe-maintainers:
    - cmutel
