{% set name = "matrix_utils" %}
{% set version = "0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2c59f6ce9ed4765073ff9b7a1ecda6180c04367cb92139f1b0a9190cf2c16fe5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools

  run:
    - bw_processing >=1.0
    - fsspec
    - numpy
    - python >=3.9
    - scipy >=1.10
    - stats_arrays

test:
  imports:
    - {{ name }}
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/brightway-lca/matrix_utils
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Utilities to build and iterate on matrices using datapackages '
  doc_url: https://3.docs.brightwaylca.org/
  dev_url: https://github.com/brightway-lca/matrix_utils

extra:
  recipe-maintainers:
    - cmutel
