{% set name = "matrix_utils" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: daf92d2217ae4f7bd16792763ad76ce614f1738e5ca71b78e3289b97dceb9086

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - bw_processing >=1.0
    - fsspec
    - numpy
    - python >={{ python_min }}
    - scipy >=1.10
    - stats_arrays

test:
  imports:
    - {{ name }}
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/brightway-lca/matrix_utils
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Utilities to build and iterate on matrices using datapackages '
  doc_url: https://3.docs.brightwaylca.org/
  dev_url: https://github.com/brightway-lca/matrix_utils

extra:
  recipe-maintainers:
    - cmutel
